In [1]:
for i in range(1,21):
    print(i,end=' ')

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 

In [2]:
for i in range(1,21,2):
    print(i,end=' ')

1 3 5 7 9 11 13 15 17 19 

In [3]:
for i in range(2,21,2):
    print(i,end=' ')

2 4 6 8 10 12 14 16 18 20 

In [4]:
for i in range(0,50,5):
    print(i,end=' ')

0 5 10 15 20 25 30 35 40 45 

In [7]:
i=0
while(i<10):
    print("Welcome",end=' ')
    i+=1

Welcome Welcome Welcome Welcome Welcome Welcome Welcome Welcome Welcome Welcome 

In [8]:
str="Welcome"

In [9]:
str

'Welcome'

In [10]:
def toprint():
    print(str)
    return
toprint()

Welcome


In [12]:
def toprint(str):
    print(str)
    return
toprint(str)

Welcome


In [13]:
a=10
def toprint(str,a):
    print(str*a)
    return
toprint(str,a)

WelcomeWelcomeWelcomeWelcomeWelcomeWelcomeWelcomeWelcomeWelcomeWelcome


In [16]:
a=10
def toprint(str):
    print(str*a,end=' ')
    return
toprint(str)

WelcomeWelcomeWelcomeWelcomeWelcomeWelcomeWelcomeWelcomeWelcomeWelcome 

In [17]:
import numpy as np

In [18]:
a=np.array([1,2,3,4,5,6])


In [19]:
print(a)

[1 2 3 4 5 6]


In [20]:
a

array([1, 2, 3, 4, 5, 6])

In [21]:
a.ndim

1

In [22]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [23]:
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
b.ndim

2

In [25]:
c=np.arange(10,30)

In [26]:
print(c)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [27]:
d=np.arange(10,31,2)


In [33]:
print(d)

[[10 12 14 16 18]
 [20 22 24 26 28]]


In [34]:
e=np.arange(10,30,2)

In [38]:
print(e)

[10 12 14 16 18 20 22 24 26 28 30]


In [39]:
print(e)

[10 12 14 16 18 20 22 24 26 28 30]


In [40]:
e=np.arange(10,29,2)

In [41]:
print(e)

[10 12 14 16 18 20 22 24 26 28]


In [43]:
e.shape=(2,5)

In [44]:
print(e)

[[10 12 14 16 18]
 [20 22 24 26 28]]


In [45]:
e.ndim

2

In [46]:
x=np.empty([3,2],dtype=int)

In [47]:
print(x)

[[-1985522336         384]
 [          0           0]
 [          1 -2147483648]]


In [48]:
x=np.zeros(10)

In [49]:
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [50]:
x=np.ones(10)
print(x)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [51]:
y=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

In [52]:
print(y)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [53]:
y.ndim

2

In [54]:
y[0]

array([1, 2, 3, 4])

In [55]:
y[1]

array([5, 6, 7, 8])

In [56]:
y[1:3]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [57]:
y[0:1]

array([[1, 2, 3, 4]])

In [58]:
y[2][2]

11

In [59]:
y[3][1:]

array([14, 15, 16])

In [60]:
y[:,1]

array([ 2,  6, 10, 14])

In [61]:
y[:,2]

array([ 3,  7, 11, 15])

In [62]:
y[:,0]

array([ 1,  5,  9, 13])

In [63]:
y[:,2:4]

array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])

In [64]:
y[1:3,0:3]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [65]:
y[0:2,0:2]

array([[1, 2],
       [5, 6]])

In [66]:
y[2:4,2:4]

array([[11, 12],
       [15, 16]])

In [67]:
z=y
print(y)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
